
// log in as Emil
POST http://localhost:5000/auth/login
Content-Type: application/json

{ "Username" : "Brugge", "Password" : "private" }

###

GET http://localhost:5000/test/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5ZjljYjU5Yi1lZDJiLTQyYWMtODA1MC0zMmI5Y2MwMTM0MWMiLCJpYXQiOiI0LzE2LzIwMjQgOTowOTo1M-KAr0FNIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiRW1haWwiOiJ0cm1vQHZpYS5kayIsIkFnZSI6IjM2IiwiZXhwIjoxNzEzMjYyMTkzLCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.-QU1tRJe3HvvkA758Hc7JuwNwRsPh4NHtZK3WBCmBnR1cXneYrYfg65rZ0C8B3gNK_8PQ366P5RS1asJkNYAPQ

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{ "Username" : "trmo", "Password" : "onetwo3FOUR" }
###
GET http://localhost:5000/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5ZjljYjU5Yi1lZDJiLTQyYWMtODA1MC0zMmI5Y2MwMTM0MWMiLCJpYXQiOiI0LzE2LzIwMjQgOTowOTo1M-KAr0FNIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiRW1haWwiOiJ0cm1vQHZpYS5kayIsIkFnZSI6IjM2IiwiZXhwIjoxNzEzMjYyMTkzLCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.-QU1tRJe3HvvkA758Hc7JuwNwRsPh4NHtZK3WBCmBnR1cXneYrYfg65rZ0C8B3gNK_8PQ366P5RS1asJkNYAPQ