# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: backend/microservices/indeklima/WebApi/Dockerfile
    ports:
      - 5200:5200
      - 7292:7292
    networks:
      - backend
    depends_on:
      - mongodb

volumes:
  mongodbdata:

networks:
  backend:
    driver: bridge
