version: "3.4"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  auth_mongodb:
    image: mongo
    container_name: auth_mongodb
    ports:
      - 27018:27017
    volumes:
      - auth_mongodbdata:/data/db
    networks:
      - backend

  indeklima_webapi:
    image: indeklima_webapi
    build:
      context: .
      dockerfile: backend/microservices/indeklima/WebApi/Dockerfile
    ports:
      - 5200:5200 #Http
      - 7292:7292 #Https
    networks:
      - backend
    depends_on:
      - mongodb

  auth_webapi:
    image: auth_webapi
    build:
      context: .
      dockerfile: backend/microservices/autorisering/WebApi/Dockerfile
    ports:
      - 5001:5001 #Http
      - 7293:7293 #Https
    networks:
      - backend
    depends_on:
      - auth_mongodb

volumes:
  mongodbdata:
  auth_mongodbdata:

networks:
  backend:
    driver: bridge
