version: "3.4"

services:
  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/mongodbdata
    networks:
      - backend

  indeklima_webapi:
    image: indeklima_webapi
    build:
      context: .
      dockerfile: backend/microservices/indeklima/WebApi/Dockerfile
    ports:
      - 5200:5200 #Http
      - 7292:7292 #Https
    networks:
      - backend
    depends_on:
      - mongo

  auth_webapi:
    image: auth_webapi
    build:
      context: .
      dockerfile: backend/microservices/autorisering/WebApi/Dockerfile
    ports:
      - 5001:5001 #Http
      - 7293:7293 #Https
    networks:
      - backend
    depends_on:
      - mongo

  broker:
    image: broker
    build:
      context: .
      dockerfile: backend/broker/Dockerfile
    ports:
      - 5202:5202 #Http
      - 7294:7294 #Https
    networks:
      - backend
    depends_on:
      - indeklima_webapi
      - auth_webapi

  frontend:
    image: frontend
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend

volumes:
  mongodbdata:
  authmongodbdata:

networks:
  backend:
    driver: bridge
