apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment-backend.yml -o k8s/
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: authwebapi
  name: authwebapi
  namespace: default
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "7293"
      port: 7293
      targetPort: 7293
  selector:
    io.kompose.service: authwebapi
status:
  loadBalancer: {}
