name: Backend build Indeklima WebApi

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend_build_broker.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x", "8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Build with dotnet
        working-directory: backend/broker
        run: dotnet build IndeklimaWebApi.csproj -c release
