name: Backend build Indeklima WebApi

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend_build_indeklima_webapi.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Build with dotnet
        working-directory: backend/microservices/indeklima/WebApi
        run: dotnet build IndeklimaWebApi.csproj -c release
