name: Branch Naming Convention

on:
  push:
    branches:
      - "*"

jobs:
  branch_naming_convention:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract target branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Check branch name
        run: |
          branch_name=${{ steps.extract_branch.outputs.branch }}

          # Define regex patterns for branch naming conventions
          backend_pattern="^backend\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          frontend_pattern="^frontend\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          iot_pattern="^iot\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          documentation_pattern="^documentation\/(backend|frontend|iot)\/[a-zA-Z0-9_-]+$"

          if [[ -z $branch_name ]]; then
            echo "Target branch not found."
            exit 1
          fi

          if [[ $branch_name =~ $backend_pattern ]]; then
              echo "Target branch '$branch_name' follows backend naming convention."
          elif [[ $branch_name =~ $frontend_pattern ]]; then
              echo "Target branch '$branch_name' follows frontend naming convention."
          elif [[ $branch_name =~ $iot_pattern ]]; then
              echo "Target branch '$branch_name' follows IoT naming convention."
          elif [[ $branch_name =~ $documentation_pattern ]]; then
              echo "Target branch '$branch_name' follows documentation naming convention."
          else
              echo "Target branch name '$branch_name' does not follow any recognized naming convention."
              exit 1
          fi
