name: 'Branch Naming Enforcement'
on:
  push:
    branches:
      - '**'  # Trigger on any push event

jobs:
  check-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures the repository is checked out in the action's workspace
      
      - name: Determine if Branch is New
        run: |
          # Extract the branch name from GitHub reference
          branch_name="${GITHUB_REF#refs/heads/}"

          # Check if the branch name is "dev" or "prod"
          if [[ "$branch_name" == "dev" || "$branch_name" == "prod" ]]; then
            echo "Branch '$branch_name' is excluded from naming check."
            exit 0
          fi

          # Check if the branch is new by fetching its reference
          if ! git show-ref --verify --quiet refs/heads/"$branch_name"; then
            echo "New branch detected: $branch_name"

            # Validate branch naming convention
            if [[ ! "$branch_name" =~ ^(iot|backend|frontend)\/(feature|documentation|bugfix)\/.*$ ]]; then
              echo "Branch name '$branch_name' does not follow the convention."
              exit 1
            else
              echo "Branch name '$branch_name' follows the convention."
            fi
          else
            echo "Branch '$branch_name' already exists, skipping naming check."
