name: Branch Naming Convention

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  branch_naming_convention:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          branch_name=$(git symbolic-ref --short HEAD)

          # Define regex patterns for branch naming conventions
          backend_pattern="^backend\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          frontend_pattern="^frontend\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          iot_pattern="^iot\/(feature|bugfix|documentation)\/[a-zA-Z0-9_-]+$"
          documentation_pattern="^documentation\/(backend|frontend|iot)\/[a-zA-Z0-9_-]+$"

          if [[ $branch_name =~ $backend_pattern ]]; then
              echo "Branch '$branch_name' follows backend naming convention."
          elif [[ $branch_name =~ $frontend_pattern ]]; then
              echo "Branch '$branch_name' follows frontend naming convention."
          elif [[ $branch_name =~ $iot_pattern ]]; then
              echo "Branch '$branch_name' follows IoT naming convention."
          elif [[ $branch_name =~ $documentation_pattern ]]; then
              echo "Branch '$branch_name' follows documentation naming convention."
          else
              echo "Branch name '$branch_name' does not follow any recognized naming convention."
              exit 1
          fi
