name: Deployment

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/deployment.yml"
  pull_request:
    paths:
      - "backend/**"

jobs:
  convert_dockercompose_to_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv ./kompose /usr/local/bin/kompose
      - name: Convert docker-compose to k8s
        run: kompose convert -f docker-compose.yml -o k8s/
      - name: Modify Kubernetes manifests for NodePort
        run: |
          sed -i 's/type: ClusterIP/type: NodePort/' k8s/*.yaml
      - name: Upload k8s files
        uses: actions/upload-artifact@v2
        with:
          name: k8s-files
          path: k8s/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Download k8s files
        uses: actions/download-artifact@v2
        with:
          name: k8s-files
          path: k8s/
      - name: Apply the k8s files
        run: |
          kubectl apply -f k8s/
      - name: List all services
        run: minikube service list
      - name: Test service URLs
        run: |
          minikube service indeklima-webapi --url
          minikube service auth-webapi --url
          minikube service broker --url
          minikube service frontend --url
          echo "-----------------opening the service URLs-----------------"
          curl $(minikube service indeklima-webapi --url)
          curl $(minikube service auth-webapi --url)
          curl $(minikube service broker --url)
      - name: Clean up
        run: |
          eval $(minikube docker-env -u)
          minikube delete
