name: IoT build and test

on: 
  pull_request:
    paths:
      - 'iot/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:
      run: cd iot && ./build-and-test.sh

